<template>
  <!-- Wrap the rendering in ClientOnly to prevent SSR issues -->
  <ClientOnly>
    <!-- Render the HTML generated by our custom renderer using v-html -->
    <!-- Restored Tailwind typography classes -->
    <div v-if="renderedHtml" class="prose max-w-none dark:prose-invert" v-html="renderedHtml"></div>
    <!-- Optional: Add a placeholder for SSR -->
    <template #fallback>
      <div class="py-4">Loading content...</div>
    </template>
  </ClientOnly>
</template>

<script setup lang="ts">
import type { PropType } from 'vue';
import { computed, toRef } from 'vue'; // Import toRef
import { useRichTextRenderer, type RichTextRoot } from '../../../composables/useRichTextRenderer'; // Corrected import path

// --- Type Definitions ---

// Define the specific block data structure expected by this component
interface ContentBlockData {
  id?: string;
  blockType: 'content';
  content: { root: RichTextRoot }; // Use the imported RichTextRoot type
}

// --- Props ---

const props = defineProps({
  block: {
    type: Object as PropType<ContentBlockData>,
    required: true,
  },
});

// --- Use Composable ---

// Pass the reactive root of the content to the composable
const contentRoot = computed(() => props.block?.content?.root);
const { renderedHtml } = useRichTextRenderer(contentRoot);

</script>
